/*
  This file is automatically generated. Any changes will be overwritten.
  Modify main-layout.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { HeaderComponent } from '@radzen/angular/dist/header';
import { SidebarToggleComponent } from '@radzen/angular/dist/sidebar-toggle';
import { ImageComponent } from '@radzen/angular/dist/image';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { SidebarComponent } from '@radzen/angular/dist/sidebar';
import { PanelMenuComponent } from '@radzen/angular/dist/panelmenu';
import { BodyComponent } from '@radzen/angular/dist/body';
import { ContentContainerComponent } from '@radzen/angular/dist/content-container';
import { FooterComponent } from '@radzen/angular/dist/footer';
import { LabelComponent } from '@radzen/angular/dist/label';

import { ConfigService } from '../config.service';


export class MainLayoutGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('header0') header0: HeaderComponent;
  @ViewChild('sidebarToggle0') sidebarToggle0: SidebarToggleComponent;
  @ViewChild('image0') image0: ImageComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('image1') image1: ImageComponent;
  @ViewChild('sidebar0') sidebar0: SidebarComponent;
  @ViewChild('panelmenu0') panelmenu0: PanelMenuComponent;
  @ViewChild('body0') body0: BodyComponent;
  @ViewChild('main') main: ContentContainerComponent;
  @ViewChild('footer0') footer0: FooterComponent;
  @ViewChild('footerText') footerText: LabelComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;
  Url: any;
  Logged: any;
  user: any;
  acesslevel: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.Url = "https://cdn.discordapp.com/avatars/512669747956154378/82904305eaf236b3c6ed419e99991e8e";

    this.Logged = false;

    this.httpClient.request('get', `${this.configService.get('serverMethodsUrl')}api/CallbackApi/GrabUserID`, {
      withCredentials: true
    })
    .subscribe((result: any) => {
      this.Url = result.url;

      this.Logged = result.logged;

      this.user = result.user;

      this.acesslevel = result.acessslevel;

      sessionStorage.setItem("level", this.acesslevel);
    }, (result: any) => {

    });
  }

  button0Click(event: any) {
    document.location.href = "https://discordapp.com/api/oauth2/authorize?client_id=688195375345041476&redirect_uri=https%3A%2F%2Fmidnightcity.xyz%2Flogin.html&response_type=code&scope=email%20identify";
  }

  image1Click(event: any) {
    this.httpClient.request('get', `${this.configService.get('serverMethodsUrl')}ServerMethods/LogOut`, {
      withCredentials: true
    })
    .subscribe((result: any) => {
      Promise.resolve().then(() => {
        sessionStorage.clear()
      }).then((result: any) => {
        location.reload();
      }, (result: any) => {

      });
    }, (result: any) => {

    });
  }
}
