/*
  This file is automatically generated. Any changes will be overwritten.
  Modify feat-line.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { GridComponent } from '@radzen/angular/dist/grid';

import { ConfigService } from '../config.service';
import { AddFeatLineComponent } from '../add-feat-line/add-feat-line.component';


export class FeatLineGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('dropdown0') dropdown0: DropDownComponent;
  @ViewChild('textbox0') textbox0: TextBoxComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('grid0') grid0: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;
  Categories: any;
  Category: any;
  Search: any;
  SearchBox: any;
  parameters: any;
  Feats: any;
  FeatsCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.httpClient.request('get', `${this.configService.get('serverMethodsUrl')}api/FeatLines/GetFeatCategories`, {
      withCredentials: true
    })
    .subscribe((result: any) => {
      this.Categories = result.value;
    }, (result: any) => {

    });

    this.Category = "All";

    this.Search = "";

    this.SearchBox = "";

    this.grid0.load();
  }

  dropdown0Change(event: any) {
    this.grid0.load();
  }

  button0Click(event: any) {
    this.Search = this.SearchBox;

    this.grid0.load();
  }

  grid0Add(event: any) {
    this.dialogService.open(AddFeatLineComponent, { parameters: {}, title: 'Add Feat Line' })
        .afterClosed().subscribe(result => {
              this.grid0.load();
    });
  }

  grid0LoadData(event: any) {
    this.httpClient.request('get', `${this.configService.get('serverMethodsUrl')}api/FeatLines/GetFeats`, {
      withCredentials: true,
      params: new HttpParams().set('Category', `${this.Category}`)
                              .set('Search', `${this.Search}`)
    })
    .subscribe((result: any) => {
      this.Feats = result.value;

      this.FeatsCount = result.count;
    }, (result: any) => {

    });
  }

  grid0RowSelect(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['show-feat-line', event.ID]);
  }
}
